### ISSUE TITLE
Archive versions of the update site / release

### ISSUE THREAD

**Issue by dvojtise** [lip6/ITSTools#10]
I'm currently stuck because the code I'm working on depends on a version of GAL of mid of  March and I haven't updated my installation at that time. (I have only an incompatible February version)
Now I wish to work on it, but can't because of the current major regression #9 .
Could you consider to deploy several versions of GAL/ITS so in case of trouble, we can at least retrieve the previous working version ? 
Ideally, this would be coupled with a release process when the code is relatively stable.

**Comment by yanntm** [comment]
we can keep history of builds but that is abit explosive.
I like the tagged release version better, I'll look into it, I think there is a feature of travis I can use for that.

**Comment by yanntm** [comment]
i'll set this up when I come back to Paris in May.

**Comment by yanntm** [comment]
We now do have releases, which contain update site as well as the binaries for tools.
