### ISSUE TITLE
Sequential composition of assignments??

### ISSUE THREAD

**Issue by francomazzanti** [lip6/ITSTools#11]
Consider the following model:
-------------------------
GAL model {
  int AA =0;
  int BB =0;
  transition aabb  [ (AA < 6 ) ] 
     { AA = AA+2 ;
        BB = AA;   }
}
main model;
property ltlaabb [ltl] :   X (AA==BB) ;
-------------------------
Is it really intended that the execution of the transition "aabb" brings the system
from state (AA=0,BB=0) to state (AA=2,BB=4)?
(therefore making false property "ltlaabb")

Which kind of "sequential composition" is that?

Regards
 Franco Mazzanti

**Comment by francomazzanti** [comment]
The problem occurs only when running itstools from the inside of Eclipse (macOS version).
Re-executing in the terminal the same command that appears on the console:
"Eclipse.app/Contents/Eclipse/plugins/fr.lip6.move.gal.itstools.binaries_1.0.0.201806011319/bin/its-lts-Darwin  -i  new_file.gal  -t  CGAL ... ... "   produces the normally expected results !!!

**Comment by francomazzanti** [comment]
The problems is caused by the fact that the original source model:
gal model{
  int AA = 0;
  int BB = 0;
  transition aabb [ AA < 6 ] {
    AA = ( AA + 2 )    ;
    BB = AA   ;
  }
}
main model;

is wrongly (?!?!)  traslated by eclipse inside the private "work" directory as:

gal model_flat{
  int AA = 0;
  int BB = 0;
  transition aabb [ AA< 6 ] {
    AA = ( AA + 2 )    ;
    BB = ( AA + 2 )    ;
  }
}
main model_flat ;

**Comment by yanntm** [comment]
Hi,
Sorry this looks like a bug or regression in the toolchain.  I'll track the problem and patch it tomorrow. I'll post here when it's fixed.

**Comment by yanntm** [comment]
ok I've tracked it down,

https://github.com/lip6/ITSTools/blob/3beb3014bb370c654ebdba16801a4402ce4c2aa4/fr.lip6.move.gal/src/fr/lip6/move/gal/support/SupportAnalyzer.java#L278-L290

this rewriting is missing on the fact that "x" depends on A.

**Comment by yanntm** [comment]
so line 286 should read : x is arbitrary but depends neither on A nor on B.

**Comment by yanntm** [comment]
So this should fix your problem if you update to the latest version (help-> check for updates) .

Thank you for reporting this problem in such audible fashion, please ask if you find any other issues or have feature requests/workflows that could be improved. LTL counter-examples are pretty tricky to interpret right now for instance.

As a side note, you might like to use : Ctrl-Shift-F shortcut to "Source->Format" to indent your gal files (it's not perfect but it's decent).
