### ISSUE TITLE
Promela to GAL transformation error

### ISSUE THREAD

**Issue by DavidFarago** [lip6/ITSTools#13]
I wanted to transform a promela file into GAL, but I get the error
"Some files were not transformed due to errors (1 files): test_row: index=0, size=0".

What does index=0, size=0 mean? How can I fix it?

The promela file contains several new language features (for-loops, select statement). Maybe they cause the error? Unfortunately, the promela code is under NDA.

**Comment by yanntm** [comment]
Closing issue as inactive, sorry the tool did not match your need.
