### ISSUE TITLE
missing dynamic library when installing its-reach on a fresh linux

### ISSUE THREAD

**Issue by dvojtise** [lip6/ITSTools#8]
On a freshly installed linux (ubuntu 17.10)
when installing itstools via eclipse and running `its-reach` contained in `fr.lip6.move.gal.itstools.binaries`.

this run fails with the following error:
> /home/dvojtise/eclipses/atsyra_studio_sdk_latest/plugins/fr.lip6.move.gal.itstools.binaries_1.0.0.201712050952/bin/its-reach-linux64: error while loading shared libraries: libgmpxx.so.4: cannot open shared object file: No such file or directory

apparently its-reach is compiled using dynamic libraries that are not part of default linux installation.

workaround : manually install libgmp
```
sudo apt-get install libgmp-dev
```

however, a better solution would be to statically include the lib

**Comment by yanntm** [comment]
ok thanks for reporting that, I'll look at the flags we need to add, I thought we had a -all-static somewhere...

**Comment by yanntm** [comment]
Ok, should be patched now (wait a bit for rebuild), please close the issue when you've tested and it works for you.

**Comment by yanntm** [comment]
build failed... I'll try another variant tomorrow, sorry.

**Comment by yanntm** [comment]
this version seems ok, rebuild is finished. Please confirm & close if this solves the issue.

**Comment by dvojtise** [comment]
ok for me with fr.lip6.move.gal.itstools.binaries_1.0.0.201712080040
